"""Merge provenance fragments into data/SOURCES.lock.json and render docs/SOURCES.md.

Every fetched source records URL, version/effective date, retrieval time and SHA-256; derived
package data files are hashed too so any edit is visible.

    uv run python -m gcg_sim.tools.sources --write
    uv run python -m gcg_sim.tools.sources --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

FRAGMENTS = Path("data/sources.d")
LOCK = Path("data/SOURCES.lock.json")
DOC = Path("docs/SOURCES.md")
DERIVED = (
    "src/gcg_sim/data/official/banlist.json",
    "src/gcg_sim/data/official/deck_construction.json",
    "src/gcg_sim/data/official/floor_rules.json",
    "src/gcg_sim/data/official/bo3_match_rules.json",
    "src/gcg_sim/data/official/edition_language.json",
    "src/gcg_sim/data/official/rules_version.json",
    "src/gcg_sim/data/overrides.json",
    "src/gcg_sim/data/curated_conflicts.json",
    "src/gcg_sim/data/rules/rules_index.json",
    "src/gcg_sim/data/rules/rules_na.json",
)
REQUIRED = (
    "id",
    "kind",
    "url",
    "version",
    "effective_date",
    "retrieved_at",
    "sha256",
    "local_path",
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_fragments(root: Path) -> tuple[list[dict[str, Any]], list[str]]:
    problems: list[str] = []
    entries: list[dict[str, Any]] = []
    for f in sorted((root / FRAGMENTS).glob("*.json")):
        for e in json.loads(f.read_text(encoding="utf-8")):
            missing = [k for k in REQUIRED if k not in e]
            if missing:
                problems.append(f"{f.name}:{e.get('id')}: missing {missing}")
            e = dict(e)
            e["fragment"] = f.name
            entries.append(e)
    ids = [e["id"] for e in entries]
    dup = sorted({i for i in ids if ids.count(i) > 1})
    if dup:
        problems.append(f"duplicate ids: {dup}")
    for e in entries:
        lp = e.get("local_path")
        if (
            lp
            and lp not in ("not-packaged",)
            and (root / lp).is_file()
            and e.get("kind") != "git-commit"
        ):
            actual = sha256(root / lp)
            if actual != e.get("sha256"):
                problems.append(f"{e['id']}: sha256 mismatch for {lp}")
    entries.sort(key=lambda e: str(e["id"]))
    return entries, problems


def build_lock(root: Path) -> tuple[dict[str, Any], list[str]]:
    entries, problems = load_fragments(root)
    derived = []
    for rel in DERIVED:
        p = root / rel
        if p.exists():
            derived.append({"path": rel, "sha256": sha256(p)})
        else:
            problems.append(f"derived file missing: {rel}")
    lock = {"schema_version": 1, "sources": entries, "derived": derived}
    return lock, problems


def render_doc(lock: dict[str, Any]) -> str:
    lines = [
        "# Sources and provenance",
        "",
        "Generated by `uv run python -m gcg_sim.tools.sources --write` from `data/sources.d/*.json`.",
        "The machine-readable lock is `data/SOURCES.lock.json`; `--check` re-verifies every hash.",
        "Only the refresh skill (`.claude/skills/gcg-refresh-data/`) touches the network; the simulator",
        "runs offline from the packaged copies.",
        "",
        "## Pinned versions",
        "",
    ]
    by_id = {e["id"]: e for e in lock["sources"]}
    commit = next((e for e in lock["sources"] if e.get("kind") == "git-commit"), None)
    if commit:
        sha = str(commit.get("url", "")).rsplit("/", 1)[-1]
        lines.append(
            f"- gcg-api: commit `{sha}`, dataset_version `{commit.get('version')}` — {commit.get('url')}"
        )
    rules = by_id.get("rules-comprehensive-en-md")
    if rules:
        lines.append(
            f"- Comprehensive Rules: Ver. {rules['version']} ({rules['effective_date']}), sha256 `{rules['sha256'][:16]}…`"
        )
    ban = next((e for e in lock["sources"] if "/en/news/01_279" in str(e.get("url"))), None)
    if ban:
        lines.append(f"- Banned & Restricted list: {ban['url']} ({ban.get('effective_date')})")
    lines += [
        "",
        "## All sources",
        "",
        "| id | kind | version / effective | retrieved (UTC) | sha256 | location |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for e in lock["sources"]:
        where = e.get("local_path") or e.get("url")
        ver = f"{e.get('version')} / {e.get('effective_date')}"
        lines.append(
            f"| {e['id']} | {e['kind']} | {ver} | {e.get('retrieved_at')} | `{str(e.get('sha256'))[:12]}` | {where} |"
        )
    lines += ["", "## Derived package data", "", "| file | sha256 |", "| --- | --- |"]
    for d in lock["derived"]:
        lines.append(f"| {d['path']} | `{d['sha256'][:16]}` |")
    lines += [
        "",
        "## Licences and attribution",
        "",
        "Contains data from gcg-api (https://gcgapi.com), made available under the Open Database License",
        "(ODbL) v1.0 — see `src/gcg_sim/data/gcgapi/LICENSE-DATA`. Card names, text and trademarks are the",
        "property of Bandai; this project is not affiliated with or endorsed by Bandai.",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=Path())
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    lock, problems = build_lock(args.root)
    text = json.dumps(lock, indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    doc = render_doc(lock)
    if args.write:
        (args.root / LOCK).write_text(text, encoding="utf-8")
        (args.root / DOC).write_text(doc, encoding="utf-8")
        print(f"wrote {LOCK} ({len(lock['sources'])} sources) and {DOC}")
    else:
        if (args.root / LOCK).read_text(encoding="utf-8") != text:
            problems.append(f"{LOCK} is out of date")
        if (args.root / DOC).read_text(encoding="utf-8") != doc:
            problems.append(f"{DOC} is out of date")
    for p in problems:
        print(p, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
