"""Generate docs/RULES_TRACEABILITY.md from rule tags in the tests and (optionally) a JUnit
result file, so each rule maps to the passing tests that verify it or to a written N/A reason.

    uv run pytest -m "" --junitxml=build/junit.xml
    uv run python -m gcg_sim.tools.traceability --junit build/junit.xml
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

from gcg_sim.rules.index import load_rules_index
from gcg_sim.tools.marks import scan

DEFAULT_OUT = Path("docs/RULES_TRACEABILITY.md")


def junit_outcomes(path: Path) -> dict[str, str]:
    """Map "file::test" (function name, parametrization stripped) to passed/failed."""
    out: dict[str, str] = {}
    root = ET.parse(path).getroot()
    for case in root.iter("testcase"):
        cls = case.get("classname", "")
        name = case.get("name", "").split("[", 1)[0]
        file = cls.replace(".", "/") + ".py" if cls else ""
        key = f"{Path(file).name}::{name}"
        failed = any(child.tag in ("failure", "error") for child in case)
        skipped = any(child.tag == "skipped" for child in case)
        status = "failed" if failed else ("skipped" if skipped else "passed")
        if out.get(key) != "failed":
            out[key] = status
    return out


def build(tests_root: Path, junit: Path | None) -> tuple[str, list[str]]:
    ri = load_rules_index()
    tags = scan(tests_root, ("rule",))
    by_rule: dict[str, list[str]] = defaultdict(list)
    for t in tags:
        test = t.test.split("::")[-1]
        by_rule[t.value].append(f"{Path(t.path).name}::{test}")
    outcomes = junit_outcomes(junit) if junit else {}
    problems: list[str] = []
    lines = [
        "# Rules traceability",
        "",
        f"Comprehensive Rules Ver. {ri.version} ({ri.date}). Generated by `gcg_sim.tools.traceability` from",
        "`@pytest.mark.rule` tags"
        + (" and the JUnit results of the full test run." if junit else "."),
        "",
        "| rule | status | tests / reason |",
        "| --- | --- | --- |",
    ]
    counts = {"tested": 0, "na": 0, "missing": 0}
    for rid in ri.ids():
        entry = ri.get(rid)
        if entry is None:
            continue
        if ri.status(rid) == "na":
            counts["na"] += 1
            lines.append(f"| {rid} | N/A | {ri.na_reason(rid)} |")
            continue
        tests = sorted(set(by_rule.get(rid, [])))
        if not tests:
            counts["missing"] += 1
            problems.append(f"rule {rid} has no test")
            lines.append(f"| {rid} | MISSING | |")
            continue
        if outcomes:
            states = [
                outcomes.get(t.split("::")[0] + "::" + t.split("::")[-1], "unknown") for t in tests
            ]
            if not any(s == "passed" for s in states):
                problems.append(f"rule {rid} has no passing test: {tests}")
        counts["tested"] += 1
        shown = ", ".join(f"`{t}`" for t in tests[:4]) + (
            f" (+{len(tests) - 4})" if len(tests) > 4 else ""
        )
        lines.append(f"| {rid} | tested ({len(tests)}) | {shown} |")
    lines[4:4] = [
        f"Summary: {counts['tested']} rules tested, {counts['na']} N/A with reasons, {counts['missing']} missing.",
        "",
    ]
    return "\n".join(lines) + "\n", problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tests", type=Path, default=Path("tests"))
    ap.add_argument("--junit", type=Path)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument(
        "--check", action="store_true", help="fail if any testable rule lacks a (passing) test"
    )
    args = ap.parse_args(argv)
    text, problems = build(args.tests, args.junit)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out}")
    for p in problems[:50]:
        print(p, file=sys.stderr)
    return 1 if (args.check and problems) else 0


if __name__ == "__main__":
    raise SystemExit(main())
